
services:
  # The Voting API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./api/src:/app/src
    
    # NEW: Environment variables for the API to connect to the database
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=votesphere
      - POSTGRES_PORT=5432

    # NEW: Tells this service to wait for the postgres service to start
    depends_on:
      - postgres

  # The Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - api